/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ChartGenerator;
import controller.Controller;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author RivaSyafri
 */
public class Dashboard extends javax.swing.JFrame {

    private Controller controller;
    
    private ChartGenerator chartGenerator;
    
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        controller = new Controller("COM11");
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChartPanel = new javax.swing.JPanel();
        ControlPanel = new javax.swing.JPanel();
        switchButton = new javax.swing.JButton();
        timeConstrainButton = new javax.swing.JButton();
        powerConstrainButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        connectButtonMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitButtonMenu = new javax.swing.JMenuItem();
        actionMenu = new javax.swing.JMenu();
        switchButtonMenu = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        constrainMenu = new javax.swing.JMenu();
        timeConstrainButtonMenu = new javax.swing.JMenuItem();
        powerConstrainButtonMenu = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        documentationButton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setPreferredSize(new java.awt.Dimension(600, 400));

        ChartPanel.setBackground(new java.awt.Color(0, 0, 0, 100));
        ChartPanel.setPreferredSize(new java.awt.Dimension(438, 150));

        javax.swing.GroupLayout ChartPanelLayout = new javax.swing.GroupLayout(ChartPanel);
        ChartPanel.setLayout(ChartPanelLayout);
        ChartPanelLayout.setHorizontalGroup(
            ChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );
        ChartPanelLayout.setVerticalGroup(
            ChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        ControlPanel.setBackground(new java.awt.Color(0, 0, 0, 200));
        ControlPanel.setPreferredSize(new java.awt.Dimension(150, 150));

        switchButton.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        switchButton.setText("SWITCH");
        switchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchButtonActionPerformed(evt);
            }
        });

        timeConstrainButton.setText("Set Time Constrain");
        timeConstrainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeConstrainButtonActionPerformed(evt);
            }
        });

        powerConstrainButton.setText("Set Power Constrain");
        powerConstrainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerConstrainButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
        ControlPanel.setLayout(ControlPanelLayout);
        ControlPanelLayout.setHorizontalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControlPanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(timeConstrainButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(switchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(powerConstrainButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        ControlPanelLayout.setVerticalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(switchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(timeConstrainButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(powerConstrainButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitButton)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        fileMenu.setText("File");

        connectButtonMenu.setText("Connect ...");
        connectButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonMenuActionPerformed(evt);
            }
        });
        fileMenu.add(connectButtonMenu);
        fileMenu.add(jSeparator1);

        exitButtonMenu.setText("Exit");
        exitButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonMenuActionPerformed(evt);
            }
        });
        fileMenu.add(exitButtonMenu);

        jMenuBar1.add(fileMenu);

        actionMenu.setText("Action");

        switchButtonMenu.setText("Switch");
        switchButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchButtonMenuActionPerformed(evt);
            }
        });
        actionMenu.add(switchButtonMenu);
        actionMenu.add(jSeparator2);

        constrainMenu.setText("Set Constrain...");

        timeConstrainButtonMenu.setText("Set Time Constrain ");
        timeConstrainButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeConstrainButtonMenuActionPerformed(evt);
            }
        });
        constrainMenu.add(timeConstrainButtonMenu);

        powerConstrainButtonMenu.setText("Set Power Constrain");
        powerConstrainButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerConstrainButtonMenuActionPerformed(evt);
            }
        });
        constrainMenu.add(powerConstrainButtonMenu);

        actionMenu.add(constrainMenu);

        jMenuBar1.add(actionMenu);

        helpMenu.setText("Help");

        documentationButton.setText("Documentation");
        documentationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentationButtonActionPerformed(evt);
            }
        });
        helpMenu.add(documentationButton);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
            .addComponent(ControlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_connectButtonMenuActionPerformed

    private void exitButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonMenuActionPerformed
        exit();
    }//GEN-LAST:event_exitButtonMenuActionPerformed

    private void switchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_switchButtonActionPerformed

    private void timeConstrainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeConstrainButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeConstrainButtonActionPerformed

    private void powerConstrainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerConstrainButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_powerConstrainButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        exit();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void switchButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchButtonMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_switchButtonMenuActionPerformed

    private void timeConstrainButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeConstrainButtonMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeConstrainButtonMenuActionPerformed

    private void powerConstrainButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerConstrainButtonMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_powerConstrainButtonMenuActionPerformed

    private void documentationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_documentationButtonActionPerformed

    private void exit() {
        System.exit(0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChartPanel;
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JMenu actionMenu;
    private javax.swing.JMenuItem connectButtonMenu;
    private javax.swing.JMenu constrainMenu;
    private javax.swing.JMenuItem documentationButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JMenuItem exitButtonMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JButton powerConstrainButton;
    private javax.swing.JMenuItem powerConstrainButtonMenu;
    private javax.swing.JButton switchButton;
    private javax.swing.JMenuItem switchButtonMenu;
    private javax.swing.JButton timeConstrainButton;
    private javax.swing.JMenuItem timeConstrainButtonMenu;
    // End of variables declaration//GEN-END:variables
}
